apiVersion: v1
kind: Service
metadata:
  name: console-web-core-ui
  labels:
    app: console-web
    chart: console-web-0.2.0
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 80
      name: http2-core-ui
      targetPort: 80
    - port: 6081
      name: status-port-core-ui
      targetPort: 6081
  selector:
    app: console-web
    release: {{ .Release.Name }}

