apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: console-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: console-web
    chart: console-web-0.2.0
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
  - console.{{ .Values.global.ingress.domainName }}
  gateways:
  - {{ .Values.global.istio.gateway.name }}
  http:
  - match:
    - uri:
        regex: /.*
    route:
    - destination:
        port:
          number: 80
        host: console-web