dex:
  tls:
    createSecret: false

global:
  isLocalEnv: false
  isBEBEnabled: false
  knative:
    false
    # Change value below to your own GitHub user name if you want point to documentation sources from your fork
    # Example: kymaOrgName: "kyma-incubator"
  kymaOrgName: "kyma-project"
  containerRegistry:
    path: eu.gcr.io/kyma-project
  ui_acceptance_tests:
    version: "37b09dbb"
  console_backend_service:
    version: "34552ff2"
  console_backend_service_test:
    version: "PR-10185"
