console:
  image:
    pullPolicy: IfNotPresent
    tag: 0fa81441
  service:
    externalPort: 80
    internalPort: 8080
    name: nginx
  statusPort: 6080
  resources: {}
core_ui:
  image:
    pullPolicy: IfNotPresent
    tag: "491eab72"
  service:
    externalPort: 80
    internalPort: 80
    name: nginx
  statusPort: 6081
  resources: {}
managementPlane: {}
replicaCount: 1
test:
  acceptance:
    labels:
      integration: true
      after-upgrade: true
    enabled: true
    ui:
      # tests uses chromium that require more memory
      limits:
        cpu: 400m
        memory: 1.5Gi
      requests:
        cpu: 350m
        memory: 900Mi
      service_catalog:
        enabled: true
      functions:
        enabled: true
      rafter:
        enabled: true
containerRegistry:
  path: eu.gcr.io/kyma-project
domainName: kyma-system
istio:
  gateway:
    name: kyma-gateway
