kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-core
  annotations:
    ingress.kubernetes.io/cache-enable: "false"    
    cert.gardener.cloud/purpose: managed
    cert.gardener.cloud/issuer: letsencrypt-production
  # annotations:
  #   nginx.ingress.kubernetes.io/backend-protocol: "true"
spec:
  tls:
  - hosts:
    - "*.ingress.chill.kyma.fun"
    secretName: cert-wildcard  
  rules:
  - host: core.ingress.chill.kyma.fun
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: console-core
            port:
              number: 8080
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-core-ui
spec:
  tls:
  - hosts:
    - "*.ingress.chill.kyma.fun"
    secretName: cert-wildcard  
  rules:
  - host: core-ui.ingress.chill.kyma.fun
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: console-core-ui
            port:
              number: 8080
