# kind: Ingress
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: core-ui
# spec:
#   rules:
#   - host: "console-core-ui.ingress.ingress.hasselhoff.shoot.canary.k8s-hana.ondemand.com"
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: console-core-ui
#             port:
#               number: 80 
