apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  generation: 1
  name: pamela
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
  service:
    host: pamela2.biggie.hasselhoff.shoot.canary.k8s-hana.ondemand.com
    name: pamela
    port: 3001
